// <auto-generated />
using Umbraco.Cms.Core.Models.PublishedContent;

namespace TestProject.Generated
{
    public partial class ContentModels
    {
        private IPublishedSnapshotAccessor _snapshotAccessor;
        
        public void Initialize(IPublishedSnapshotAccessor accessor)
        {
            _snapshotAccessor = accessor;
        }
        
        public IPublishedSnapshot GetSnapshot()
        {
            return _snapshotAccessor.GetRequiredPublishedSnapshot();
        }
    }
}
